default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  host: localhost
  username: foobar
  password: password

development:
  <<: *default
  database: test_task_development

test:
  <<: *default
  database: test_task_test

production:
  <<: *default
  database: test_task_production

